id: Vendr.Checkout
name: Checkout
type: Package
description: 
supportedBy: core

packageVersion: 2.1.2
docVersions:
  next: 
  current: 2.0.0
  previous: 
    - 1.1.0
    - 1.0.0

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/