id: Vendr.Checkout
name: Checkout
type: Package
description: 
supportedBy: core

packageVersion: 3.1.0
docVersions:
  next: 
  current: 3.0.0
  previous: 
    - 2.0.0
    - 1.1.0
    - 1.0.0

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/