id: Vendr
name: Vendr
type: Product
description: 
supportedBy: core

packageVersion: 2.4.0
docVersions:
  next: 3.0.0
  current: 2.1.0
  previous: 
  - 1.8.0
  - 1.5.0
  - 1.4.0
  - 1.3.0
  - 1.2.0
  - 1.0.0

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/
