id: Vendr.PaymentProviders.CheckoutDotCom
name: Checkout.com
logo: checkout-dot-com.svg
type: PaymentProvider
supportedBy: community

packageVersion: 1.0.0
docVersions:
  next: 
  current: 1.0.0
  previous: 

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/