id: Vendr.PaymentProviders.Klarna
name: Klarna
logo: klarna.svg
type: PaymentProvider
supportedBy: core

packageVersion: 2.0.3
docVersions:
  next: 
  current: 0.1.0
  previous: 

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/